#%RAML 1.0 Library
usage: These types relate to statistics.
uses:
  position: position.raml
types:
  positions_to_do:
    type: array
    items: position.position
    description: Positions left to process
  positions_processing:
    type: array
    items: position.position
    description: Positions currently being processed
  positions_completed:
    type: integer
    description: How many positions have been analyzed matching the criteria
