#%RAML 1.0 Library
usage: These types relate to statistics.
types:
  positions_to_do:
    type: integer
    description: How many positions are left to process
  positions_processing:
    type: integer
    description: How many positions are currently being processed
  positions_completed:
    type: integer
    description: How many positions have been analyzed matching the criteria
